### GENERAL SETTINGS ###
# Site Settings
title: Jon Starnes
about: This site is a personal site for data science projects that uses open access data.
email: jstarne4@gmail.com
description: >
  Grokking it with Open Data
baseurl: ""
url: "http://localhost:4000/"
timezone: America/New_York

read: Read More

author:
  name:     Jon Starnes
  link:     https://jon-starnes.github.io
  photo:
    alt:    Avatar from GitHub
    remote: https://avatars0.githubusercontent.com/u/14081406?v=3&s=460
#    local: assets/img/photo.jpg
  secondary: "#282d2e" # Now dark gray tint of primary - original #384452 "#33004D"

twitter_username: starj0n
github_username:  jon-starnes
analytics: #Google analytics code in the format XX-nnnnnnnn-n
# url: "https://github.com/jon-starnes/jon-starnes.github.io"

github:
  user: jon-starnes
  repo: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--mor#00f345e--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

highlighter: rouge

colors:  #in hex code if not noted else
  primary: "#00aef3" #"#F70031"
  primary_rgb: "0,174,243" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#282d2e" # Now dark gray tint of primary - original #384452 "#33004D"
  link: "#0077a7" #
  link_hover: "#00da3e" #  variant of this lime green #00f345 original is #01b2fe
  footer_heading: "#9c9c9c" # white
  footer_content: "#8f8f8f" # light gray


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
#  - title: dribbble
#    url:
  - title: facebook
    url: https://www.facebook.com/GrokkinGIOD
  - title: twitter
    url: https://twitter.com/starj0n
  - title: github
    url: https://github.com/jon-starnes
#  - title: tumblr
#    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
#    - P.O. Box 92
    - Cartersville, GA 30121
    - United States.
email: jstarne4@gmail.com
# tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Jon Starnes
    position: Main Conspirator
    text: "The more we find the more we realize"
    img: jon-s.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
#  - name: dribbble
#    img: client01.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
# about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem # Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message:
#    author: Robert Heinlein
#    position: Author
